spring.application.name=sistemas

server.port=8089

# URL de conexão (Ex: jdbc:mysql://localhost:3306/nome_banco):
spring.datasource.url=jdbc:mariadb://localhost:3306/gwj2

# Usuário do banco
spring.datasource.username=desenvolvedor

# Senha do banco
spring.datasource.password=b2#FbXPQTu4FYw

# Driver do banco (Opcional no Spring moderno, mas bom ter)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Prefixo das tabelas do banco de dados
app.database.prefix=tab_

# Configuração para identificação dinâmica de entidades nos templates
app.entity.package=com.gwj.model.domain