flowchart LR
    %% Atores
    Cliente([👤 Cliente])

    %% Fronteira do Sistema
    subgraph Sistema [Sistema Tgo's Barbearia]
        direction TB
        UC1(Explorar Catálogo e Serviços)
        UC2(Agendar Horário)
        UC3(Selecionar Profissional e Data)
        UC4(Realizar Checkout)
        UC5(Definir Forma de Pagamento)
        UC6(Receber Confirmação e Recibo)
    end

    %% Associações Principais
    Cliente ===> UC1
    Cliente ===> UC2
    Cliente ===> UC4
    Cliente ===> UC6

    %% Dependências (Includes)
    UC2 -. "<< include >>" .-> UC3
    UC4 -. "<< include >>" .-> UC5
